### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by mfranchini** [shbatm/MMM-OnScreenMenu#37]
Hi
I installed OnScreenMenu and this is my configuration:
                {
                        module: 'MMM-OnScreenMenu',
                        position: 'center',
                        /* Valid positions: 'top_right', 'top_left', 'bottom_right', 'bottom_left' */
                        config: {
                                touchMode: false,
                                menuItems: {
                                    stop: { title: "Stop MM", icon: "power-off", source: "ALL" },
                                    restart: { title: "Restart MagicMirror", icon: "recycle", source: "ALL" },
                                    //refresh: { title: "Refresh MagicMirror", icon: "refresh", source: "LOCAL" },
                                    //reboot: { title: "Reboot", icon: "spinner", source: "ALL" },
                                    //shutdown: { title: "Shutdown", icon: "power-off", source: "ALL" },
                                },
                                enableKeyboard: true,
                        }
                },

but when i touch the screen in terminal raise this error:

[06.11.2023 18:54.26.669] [LOG]   Error: process name not found
    at /home/pi/MagicMirror/modules/MMM-OnScreenMenu/node_modules/pm2/lib/API.js:1398:24
    at /home/pi/MagicMirror/modules/MMM-OnScreenMenu/node_modules/pm2/lib/Client.js:697:12
    at /home/pi/MagicMirror/modules/MMM-OnScreenMenu/node_modules/pm2-axon-rpc/lib/client.js:45:10
    at Parser.<anonymous> (/home/pi/MagicMirror/modules/MMM-OnScreenMenu/node_modules/pm2-axon/lib/sockets/req.js:67:8)
    at Parser.emit (node:events:513:28)
    at Parser._write (/home/pi/MagicMirror/modules/MMM-OnScreenMenu/node_modules/amp/lib/stream.js:91:16)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Parser.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)

and this

[06.11.2023 20:25.50.140] [ERROR] (node:3397) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `electron --trace-warnings ...` to show where the warning was created)
[06.11.2023 20:25.50.142] [ERROR] (node:3397) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
[06.11.2023 20:25.50.142] [ERROR] (node:3397) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
[06.11.2023 20:25.50.143] [ERROR] (node:3397) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
[06.11.2023 20:25.50.143] [ERROR] (node:3397) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
[06.11.2023 20:25.50.144] [ERROR] (node:3397) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
[06.11.2023 20:25.50.144] [ERROR] (node:3397) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
[06.11.2023 20:25.50.145] [ERROR] (node:3397) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
[06.11.2023 20:25.50.145] [ERROR] (node:3397) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
[06.11.2023 20:25.50.146] [ERROR] (node:3397) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
[06.11.2023 20:25.50.147] [ERROR] (node:3397) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
[06.11.2023 20:25.50.147] [ERROR] (node:3397) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
[06.11.2023 20:25.50.148] [ERROR] (node:3397) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
[06.11.2023 20:25.50.149] [ERROR] (node:3397) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
[06.11.2023 20:25.50.149] [ERROR] (node:3397) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
[06.11.2023 20:25.50.150] [ERROR] (node:3397) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
[06.11.2023 20:25.50.150] [ERROR] (node:3397) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
[06.11.2023 20:25.50.151] [ERROR] (node:3397) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
[06.11.2023 20:25.50.151] [ERROR] (node:3397) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
[06.11.2023 20:25.50.151] [ERROR] (node:3397) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
[06.11.2023 20:25.50.152] [ERROR] (node:3397) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
[06.11.2023 20:25.50.152] [ERROR] (node:3397) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
[06.11.2023 20:25.50.153] [ERROR] (node:3397) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
[06.11.2023 20:25.50.153] [ERROR] (node:3397) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
[06.11.2023 20:25.50.153] [ERROR] (node:3397) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
[06.11.2023 20:25.50.154] [ERROR] (node:3397) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
[06.11.2023 20:25.50.154] [ERROR] (node:3397) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
[06.11.2023 20:25.50.155] [ERROR] (node:3397) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
[06.11.2023 20:25.50.155] [ERROR] (node:3397) Warning: Accessing non-existent property 'which' of module exports inside circular dependency

and widget stop working, can you help me?

Thanks

**Comment by mfranchini** [comment]
Close issue, i have solved. my error
Thanks
